controllers/UserController.php
<?php

namespace app\controllers;

use app\behaviors\RoleBehavior;
use app\models\forms\AvatarForm;

use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use app\models\forms\ResetPasswordForm;
use yii\web\UploadedFile;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['index','create','update','view'],
                'rules' => [
                    // allow authenticated users
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    // everything else is denied
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {

        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     *
     */
    public function actionProfile()
    {
        $request = Yii::$app->request;
        $model = Yii::$app->user->identity;
        $model->scenario = User::SCENARIO_EDIT;

        if($model->load($request->post()) && $model->save()){

            Yii::$app->session->setFlash('success', 'Изменения сохранены');

            return $this->render('profile', [
                'model' => $model,
            ]);
        }

        return $this->render('profile', [
            'model' => $model,
        ]);
    }

    /*

    /**
     * Updates an existing User model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id, $containerPjaxReload = '#crud-datatable-pjax')
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);
        $model->scenario = User::SCENARIO_EDIT;

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Изменить пользователя #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];         
            }else if($model->load($request->post()) && $model->save()){

                $model->save();
                return [
                    'forceReload'=>$containerPjaxReload,
                    'forceClose' => true,
                ];
            }else{
                 return [
                    'title'=> "Изменить пользователя #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];        
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $request = Yii::$app->request;


        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                    'title'=> "пользователь #".$id,
                    'content'=>$this->renderAjax('view', [
                        'model' => $this->findModel($id),
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Изменить',['update','id'=>$id],['class'=>'btn btn-primary','role'=>'modal-remote'])
                ];
        }else{
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * Экшен для изменения логина прямо из таблицы. С помощью плагина Editable
     * @param $id
     * @return array
     */
    public function actionEditLogin($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $model = User::find()->where(['id'=>$id])->one();
        $model->scenario = User::SCENARIO_EDIT;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return ['output' => $model->login, 'message' => null];
        }else{
            $errors = $model->getFirstErrors();
            $error = reset($errors);
            return ['output' => $model->login, 'message' => $error];
        }
    }

    /**
     * Экшен для изменения логина прямо из таблицы. С помощью плагина Editable
     * @param $id
     * @return array
     */
    public function actionEditName($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $model = User::find()->where(['id'=>$id])->one();
        $model->scenario = User::SCENARIO_EDIT;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return ['output' => $model->name, 'message' => null];
        }else{
            $errors = $model->getFirstErrors();
            $error = reset($errors);
            return ['output' => $model->name, 'message' => $error];
        }
    }

    /**
     * Creates a new User model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new User();

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Добавить пользователя",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-white pull-left btn-sm','data-dismiss'=>"modal"]).
                                Html::button('Создать',['class'=>'btn btn-primary btn-sm','type'=>"submit"])

                ];
            }else if($model->load($request->post()) && $model->save()){


                $model->save();
                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'title'=> "Добавить пользователя",
                    'content'=>'<span class="text-success">Создание пользователя успешно завершено</span>',
                    'footer'=> Html::button('ОК',['class'=>'btn btn-default btn-sm pull-left','data-dismiss'=>"modal"]).
                            Html::a('Создать еще',['create'],['class'=>'btn btn-primary btn-sm','role'=>'modal-remote'])

                ];
            }else{           
                return [
                    'title'=> "Добавить пользователя",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default btn-sm pull-left','data-dismiss'=>"modal"]).
                                Html::button('Создать',['class'=>'btn btn-primary btn-sm','type'=>"submit"])
        
                ];         
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }
       
    }

    /**
     * @param string $q
     * @return array
     */
    public function actionSearchKind($q){
        Yii::$app->response->format = Response::FORMAT_JSON;
        $pks = explode(',', $q);

        $list = [];
        $type = WorkType::find()->where(['id' => $pks])->all();
        foreach ($type as $item) {
            $kings = WorkKind::find()->where(['work_type_id' => $item->id])->all();
            foreach ($kings as $king) {
                $list[$item->name][$king->name] = ArrayHelper::map(Subgroups::find()->where(['work_kind_id' => $king->id])->all(), 'id', 'name');
            }
        }

        return $list;
    }

    /**
     * Изменяет пароль у конкретного пользователя
     * @param $id
     * @return array
     */

views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use yii\widgets\Pjax;

?>
<script async="" src="https://www.google-analytics.com/analytics.js"></script>
<div id="page-loader" class="fade in"><span class="spinner"></span></div>
<div class="content" id="content">

        <?php Pjax::begin(['enablePushState' => false, 'id' => 'report-messages-pjax']) ?>
        <?php if(Yii::$app->session->hasFlash('success')): ?>
            <div class="alert alert-success fade in m-b-15">
                <strong>Успех!</strong>
                <?=Yii::$app->session->getFlash('success')?>
                <span class="close" data-dismiss="alert">×</span>
                <div>

                </div>
            </div>
        <?php endif; ?>

        <?php if(Yii::$app->session->hasFlash('info')): ?>
            <div class="alert alert-info fade in m-b-15">
                <strong>Уведомление!</strong>
                <?=Yii::$app->session->getFlash('info')?>
                <span class="close" data-dismiss="alert">×</span>
                <div>

                </div>
            </div>
        <?php endif; ?>

        <?php if(Yii::$app->session->hasFlash('warning')): ?>
            <div class="alert alert-warning fade in m-b-15">
                <strong>Внимание!</strong>
                <?=Yii::$app->session->getFlash('warning')?>
                <span class="close" data-dismiss="alert">×</span>
                <div>

                </div>
            </div>
        <?php endif; ?>

        <?php if(Yii::$app->session->hasFlash('error')): ?>
            <div class="alert alert-danger fade in m-b-15">
                <strong>Ошибка!</strong>
                <?=Yii::$app->session->getFlash('error')?>
                <span class="close" data-dismiss="alert">×</span>
                <div>

                </div>
            </div>
        <?php endif; ?>
        <?php Pjax::end() ?>

        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1 class="page-header">Basic Tables</h1>
        <?php } else { ?>
        <?php } ?>

<!--         <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?> -->

        <?= $content ?>
    </div>

views/layouts/header-menu.php
<?php

use yii\helpers\Url;

?>

<div id="top-menu" class="top-menu">
    <?php if(Yii::$app->user->isGuest == false): ?>
        <?php
        echo \app\admintheme\widgets\Menu::widget(
            [
                'options' => ['class' => 'nav'],
                'items' => [

                    ['label' => 'Заказы', 'icon' => 'fa  fa-flag', 'url' => ['/order'],],
                    ['label' => 'Пользователи', 'icon' => 'fa  fa-user-o', 'url' => ['/user'], 'visible' => Yii::$app->user->identity->isSuperAdmin()],
                    ['label' => 'Номенклатура', 'icon' => 'fa fa-sitemap', 'url' => ['/nomenclature'],],
                    ['label' => 'Статус', 'icon' => 'fa fa-area-chart', 'url' => ['/status'],],

            ]
    ]
        );
        ?>
    <?php endif; ?>
</div>

views/layouts/header.php
<?php

use yii\helpers\Html;
use app\models\Users;

?>

<div id="header" class="header navbar navbar-default navbar-fixed-top">
            <!-- begin container-fluid -->
            <div class="container-fluid">
                <!-- begin mobile sidebar expand / collapse button -->
                <div class="navbar-header">
                    <a href="<?=Yii::$app->homeUrl?>" class="navbar-brand">
                        <span>
                           GREENEX
                        </span>
                    </a>
                    <button type="button" class="navbar-toggle" data-click="top-menu-toggled">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <!-- end mobile sidebar expand / collapse button -->

                <?php if(Yii::$app->user->isGuest == false): ?>
                    <!-- begin header navigation right -->
                    <ul class="nav navbar-nav navbar-right">
                        <li class="navbar-user">
                            <?= Html::a('<i class="fa fa-question-circle" style="font-size: 20px;"></i>', ['ticket/index'], ['title' => 'Тикеты', 'style' => 'cursor: pointer;']) ?>
                        </li>
                        <li class="dropdown navbar-user">
                            <a id="btn-dropdown_header" href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="/" style="object-fit: cover;" data-role="avatar-view" alt="">
                                <span class="hidden-xs"><?=Yii::$app->user->identity->login?></span> <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu animated fadeInLeft">
                                <li class="arrow"></li>
                                <li> <?= Html::a('Настройки пользователи', ['user/profile']) ?> </li>
                                <li class="divider"></li>
                                <li> <?= Html::a('Выйти', ['/site/logout'], ['data-method' => 'post']) ?> </li>
                            </ul>
                        </li>
                    </ul>
                    <!-- end header navigation right -->
                <?php endif; ?>
            </div>
            <!-- end container-fluid -->
        </div>

views/layouts/main-login.php
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <title>Авторизация</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />

    <!-- ================== BEGIN BASE CSS STYLE ================== -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <link href="/theme/assets/plugins/jquery-ui/themes/base/minified/jquery-ui.min.css" rel="stylesheet" />
    <link href="/theme/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/theme/assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="/theme/assets/css/animate.min.css" rel="stylesheet" />
    <link href="/theme/assets/css/style.min.css" rel="stylesheet" />
    <link href="/theme/assets/css/style-responsive.min.css" rel="stylesheet" />
    <!-- ================== END BASE CSS STYLE ================== -->

    <!-- ================== BEGIN BASE JS ================== -->
    <script src="/theme/assets/plugins/pace/pace.min.js"></script>
    <!-- ================== END BASE JS ================== -->
</head>
<body class="pace-top">
<!-- begin #page-loader -->
<div id="page-loader" class="fade in"><span class="spinner"></span></div>
<!-- end #page-loader -->

<!-- begin #page-container -->
<div id="page-container" class="fade">
    <!-- begin login -->
    <?=$content?>
    <!-- end login -->

</div>
<!-- end page container -->

<!-- ================== BEGIN BASE JS ================== -->
<script src="/theme/assets/plugins/jquery/jquery-1.9.1.min.js"></script>
<script src="/theme/assets/plugins/jquery/jquery-migrate-1.1.0.min.js"></script>
<script src="/theme/assets/plugins/jquery-ui/ui/minified/jquery-ui.min.js"></script>
<script src="/theme/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
<!--[if lt IE 9]>
<script src="/theme/assets/plugins/crossbrowserjs/html5shiv.js"></script>
<script src="/theme/assets/plugins/crossbrowserjs/respond.min.js"></script>
<script src="/theme/assets/plugins/crossbrowserjs/excanvas.min.js"></script>
<![endif]-->
<script src="/theme/assets/plugins/slimscroll/jquery.slimscroll.min.js"></script>
<script src="/theme/assets/plugins/jquery-cookie/jquery.cookie.js"></script>
<!-- ================== END BASE JS ================== -->

<!-- ================== BEGIN PAGE LEVEL JS ================== -->
<script src="/theme/assets/js/apps.min.js"></script>
<!-- ================== END PAGE LEVEL JS ================== -->

<script>
    $(document).ready(function() {
        App.init();
    });
</script>
</body>
</html>

views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this \yii\web\View */
/* @var $content string */

//$isGuest = Yii::$app->user->isGuest;
//if($isGuest)
//    $theme = 'default';
//else
//    $theme = Yii::$app->user->identity->theme;


if (Yii::$app->controller->action->id === 'login') { 
/**
 * Do not use this code in your template. Remove it. 
 * Instead, use the code  $this->layout = '//main-login'; in your controller.
 */
    echo $this->render(
        'main-login',
        ['content' => $content]
    );
} else {

    if (class_exists('backend\assets\AppAsset')) {
        backend\assets\AppAsset::register($this);
    } else {
        app\assets\AppAsset::register($this);
    }

    app\assets\ColorAdminAsset::register($this);

    // dmstr\web\AdminLteAsset::register($this);

    if(isset($this->params['minified-menu']) && $this->params['minified-menu'] == true){
        $minifiedMenu = true;
    } else {
        $minifiedMenu = false;
    }
//    $minifiedMenu = true;
    $directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
    ?>
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <!-- ================== BEGIN BASE CSS STYLE ================== -->
        <?=$this->head()?>
        <link href="/theme/assets/css/theme/default.css" rel="stylesheet">
        <!-- ================== END BASE CSS STYLE ================== -->
        <script src="/theme/assets/plugins/jquery/jquery-1.9.1.min.js"></script>
<!--        <script src="/assets/pace/pace.min.js"></script>-->
    </head>
    <body>

    <?php $this->beginBody() ?>

    <?php if($minifiedMenu){
        $class = 'page-container page-sidebar-fixed page-sidebar-minified fade page-header-fixed in';
    } else {
        $class = 'page-container page-sidebar-fixed fade page-header-fixed in';
    }

    ?>

    <div id="page-container" class="page-container page-without-sidebar page-with-top-menu fade page-header-fixed in">
        <?= $this->render(
            'header.php',
            ['directoryAsset' => $directoryAsset]
        ) ?>

        <?= $this->render(
            'header-menu.php',
            ['directoryAsset' => $directoryAsset]
        )?>


        <?= $this->render(
            'content.php',
            ['content' => $content, 'directoryAsset' => $directoryAsset]
        ) ?>

        <?= $this->render(
            'settings.php'
        ) ?>

    </div>


    <div class="hidden">
        <?php $avatar = new \app\models\forms\AvatarForm(); $avatarForm = ActiveForm::begin(['id' => 'avatar-form', 'action' => ['user/upload-avatar'], 'options' => ['enctype' => 'multipart/form-data']])  ?>

        <?= $avatarForm->field($avatar, 'file')->fileInput() ?>

        <?php ActiveForm::end() ?>
    </div>


    <?php $this->endBody() ?>

    <script>
        $(document).ready(function() {
            App.init();
        });
    </script>

    

    <?=$this->render(
        'main-script.php'
    ) ?>
<style>
[title='Выберите формат файла для экспорта']{
    padding: 3px !important;
    padding-bottom: 2px !important;
}
</style>

    </body>
    </html>
    <?php $this->endPage() ?>
<?php } ?>

views/layouts/settings.php
<div class="theme-panel" style="display: none;">
            <a href="javascript:;" data-click="theme-panel-expand" class="theme-collapse-btn"><i class="fa fa-cog"></i></a>
            <div class="theme-panel-content">
                <h5 class="m-t-0">Color Theme</h5>
                <ul class="theme-list clearfix">
                    <li class=""><a href="javascript:;" class="bg-green" data-theme="default" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Default" data-original-title="" title="">&nbsp;</a></li>
                    <li><a href="javascript:;" class="bg-red" data-theme="red" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Red" data-original-title="" title="">&nbsp;</a></li>
                    <li><a href="javascript:;" class="bg-blue" data-theme="blue" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Blue" data-original-title="" title="">&nbsp;</a></li>
                    <li><a href="javascript:;" class="bg-purple" data-theme="purple" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Purple" data-original-title="" title="">&nbsp;</a></li>
                    <li class="active"><a href="javascript:;" class="bg-orange" data-theme="orange" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Orange" data-original-title="" title="">&nbsp;</a></li>
                    <li><a href="javascript:;" class="bg-black" data-theme="black" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Black" data-original-title="" title="">&nbsp;</a></li>
                </ul>
                <div class="divider"></div>
                <div class="row m-t-10">
                    <div class="col-md-5 control-label double-line">Header Styling</div>
                    <div class="col-md-7">
                        <select name="header-styling" class="form-control input-sm">
                            <option value="1">default</option>
                            <option value="2">inverse</option>
                        </select>
                    </div>
                </div>
                <div class="row m-t-10">
                    <div class="col-md-5 control-label">Header</div>
                    <div class="col-md-7">
                        <select name="header-fixed" class="form-control input-sm">
                            <option value="1">fixed</option>
                            <option value="2">default</option>
                        </select>
                    </div>
                </div>
                <div class="row m-t-10">
                    <div class="col-md-5 control-label double-line">Sidebar Styling</div>
                    <div class="col-md-7">
                        <select name="sidebar-styling" class="form-control input-sm">
                            <option value="1">default</option>
                            <option value="2">grid</option>
                        </select>
                    </div>
                </div>
                <div class="row m-t-10">
                    <div class="col-md-5 control-label">Sidebar</div>
                    <div class="col-md-7">
                        <select name="sidebar-fixed" class="form-control input-sm">
                            <option value="1">fixed</option>
                            <option value="2">default</option>
                        </select>
                    </div>
                </div>
                <div class="row m-t-10">
                    <div class="col-md-5 control-label double-line">Sidebar Gradient</div>
                    <div class="col-md-7">
                        <select name="content-gradient" class="form-control input-sm">
                            <option value="1">disabled</option>
                            <option value="2">enabled</option>
                        </select>
                    </div>
                </div>
                <div class="row m-t-10">
                    <div class="col-md-5 control-label double-line">Content Styling</div>
                    <div class="col-md-7">
                        <select name="content-styling" class="form-control input-sm">
                            <option value="1">default</option>
                            <option value="2">black</option>
                        </select>
                    </div>
                </div>
                <div class="row m-t-10">
                    <div class="col-md-12">
                        <a href="#" class="btn btn-inverse btn-block btn-sm" data-click="reset-local-storage"><i class="fa fa-refresh m-r-3"></i> Reset Local Storage</a>
                    </div>
                </div>
            </div>
        </div>